[project]
site_name = "Mój Homelab"
description = "Moje ściągawki i konfiguracje"

[theme]
name = "modern"

# Definiujemy dwie palety. Ta, która jest pierwsza na liście, ładuje się jako domyślna.
[[theme.palette]]
media = "(prefers-color-scheme)"
scheme = "slate"       # Włącza ciemne tło (Slate)
primary = "teal"       # Morskie nagłówki i ikony
accent = "teal"
toggle.icon = "lucide/sun"
toggle.name = "Przełącz na jasny motyw"

[[theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"     # Opcjonalna jasna paleta na wypadek przełączenia
primary = "teal"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Przełącz na ciemny motyw"

[markdown]
extensions = [
    "admonition",
    "pymdownx.superfences",
    "pymdownx.highlight"
]
