[project]
site_name = "Mój Homelab"
description = "Moje ściągawki i konfiguracje"

[theme]
name = "modern"
# Zensical akceptuje dla ciemnego trybu wyłącznie słowo "slate"
scheme = "slate" 

[markdown]
extensions = [
    "admonition",
    "pymdownx.superfences",
    "pymdownx.highlight"
]
